openapi: 3.0.0
info:
  title: My API
  version: 1.0.0
  description: API documentation using Swagger
paths:
  /getUsers:
    get:
      $ref: "./routes/getUsers.yaml"
  /Newuser:
    post:
      $ref: "./routes/newUser.yaml"
